# Data
root: ../../data
dataset: Amazon2023Instruments_550_LOU

# Model
maxlen: 50
num_heads: 2
num_blocks: 4
embedding_dim: 64
linear_hidden_dim: 4
attention_dim: 4
emb_dropout_rate: 0.5
hidden_dropout_rate: 0.3
num_negs: 512
temperature: 0.1
num_buckets: 128

# Training
epochs: 300
batch_size: 256
optimizer: AdamW
lr: 0.005
weight_decay: 0.0

# Evaluation
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, HitRate@20, HitRate@50, NDCG@5, NDCG@10, NDCG@20, NDCG@50]
which4best: NDCG@10
