root: ../../data
dataset: MovieLens1M_500_LOU

maxlen: 200
num_heads: 2
num_blocks: 8
embedding_dim: 50
linear_hidden_dim: 25
attention_dim: 25
emb_dropout_rate: 0.2
hidden_dropout_rate: 0.2

epochs: 300
batch_size: 128
optimizer: AdamW
lr: 1.e-3
weight_decay: 0.
beta1: 0.9
beta2: 0.98
num_negs: 128

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10