# Data
root: ../../data
dataset: Amazon2014Sports_550_LOU
tasktag: NEXTITEM
sem_feat_file: sentence-t5-xl_title_categories_brand.pkl

# Model
num_codewords: 256
num_codebooks: 3
codebook_dim: 128
hidden_dims: 512,256,128
apply_shared_codebook: false
sk_epsilons: 0.,0.,0.
sk_iters: 50
commit_weight: 0.5
dropout_rate: 0.

# Training
epochs: 10000
batch_size: 1024
optimizer: AdamW
lr: 5.e-4
weight_decay: 0.0

# Evaluation
eval_freq: 100
CHECKPOINT_FREQ: 100
which4best: PPL