root: ../../data
dataset: Amazon2014Beauty_550_LOU

maxlen: 50
num_layers: 3
embedding_dim: 64

lr: 1.e-3
epochs: 100
batch_size: 512
optimizer: adamw
weight_decay: 1.e-6
dropout_rate: 0.7

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10