root: ../../data
dataset: Amazon2014Baby_550_MMRec

embedding_dim: 64
num_layers: 3
norm_mode: PN
norm_scale: 10

epochs: 1000
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-2

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20