# Data
root: ../../data
dataset: Amazon2023Instruments_550_LOU

# Model
maxlen: 50
num_blocks: 1
num_heads: 4
embedding_dim: 64
attn_dropout_rate: 0.5
hidden_dropout_rate: 0.1
pvn_weight: 0.001
distance_metric: wasserstein

# Training
epochs: 500
batch_size: 512
optimizer: adam
lr: 0.0001
weight_decay: 0.0001

# Evaluation
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, HitRate@20, HitRate@50, NDCG@5, NDCG@10, NDCG@20, NDCG@50]
which4best: NDCG@10
