root: ../../data
dataset: Yelp2019_550_S3Rec

maxlen: 50
num_blocks: 1
num_heads: 4
embedding_dim: 64

epochs: 500
batch_size: 512
optimizer: adam
attn_dropout_rate: 0.1
hidden_dropout_rate: 0.4
lr: 5.e-4
weight_decay: 0.

pvn_weight: 0.001
distance_metric: wasserstein

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10