# Data
root: ../../data
dataset: Yelp2019_550_S3Rec

# Model
maxlen: 50
num_blocks: 1
num_heads: 4
embedding_dim: 64
attn_dropout_rate: 0.1
hidden_dropout_rate: 0.4
pvn_weight: 0.001
distance_metric: wasserstein

# Training
epochs: 500
batch_size: 512
optimizer: adam
lr: 5.e-4
weight_decay: 0.

# Evaluation
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10
