# Data
root: ../../data
dataset: Amazon2014Clothing_550_MMRec

# Model
embedding_dim: 64
num_layers: 1
fusion_mode: add
vfile: visual_modality.pkl
tfile: textual_modality.pkl
afile: Null

# Training
epochs: 50
batch_size: 1024
optimizer: adam
lr: 1.e-4
weight_decay: 5.e-5
eval_freq: 1

# Evaluation
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, HitRate@20, HitRate@50, NDCG@5, NDCG@10, NDCG@20, NDCG@50]
which4best: NDCG@10
