root: ../../data
dataset: Yelp2019_550_S3Rec

maxlen: 50
embedding_dim: 64
hidden_size: 128
emb_dropout_rate: 0.7
hidden_dropout_rate: 0.
num_blocks: 1

epochs: 300
batch_size: 512
lr: 5.e-4
weight_decay: 1.e-4
loss: BCE

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10