dataset: Amazon2014Baby_550_MMRec
root: ../../data

embedding_dim: 64
num_layers: 1

epochs: 500
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-4

dropout: 0.5
second_l: 2.
reg_weight: 1.e-1

vfile: visual_modality.pkl
tfile: textual_modality.pkl
afile: Null

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20