root: ../../data
dataset: Amazon2014Beauty_550_LOU

maxlen: 50
num_heads: 1
num_blocks: 2
embedding_dim: 64
hidden_dropout_rate: 0.2
attn_dropout_rate: 0.5

epochs: 500
batch_size: 512
optimizer: Lion
lr: 1.e-4
beta1: 0.9
beta2: 0.99
weight_decay: 0.5
loss: BCE

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10