root: ../../data
dataset: Amazon2014Beauty_10100_LOU
tasktag: NEXTITEM

maxlen: 50
num_heads: 1
num_blocks: 2
embedding_dim: 64
dropout_rate: 0.2

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-3
weight_decay: 0.
loss: BCE

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10