root: ../../data
dataset: Yelp2018_10104811_ROU

embedding_dim: 8
hidden_sizes: "64,32,16,8"

epochs: 200
batch_size: 1024
optimizer: adam
lr: 1.e-3
weight_decay: 0.
num_negs: 4

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20