root: ../../data
dataset: Yelp2019_550_S3Rec

maxlen: 50
num_heads: 4
num_blocks: 2
hidden_size: 64
dropout_rate: 0.3
mask_prob: 0.5

epochs: 500
batch_size: 256
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-6

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10