root: ../../data
dataset: Yelp2018_10104811_ROU

gamma: .5
embedding_dim: 64

lr: 1.e-4
weight_decay: 1.e-8
epochs: 100
batch_size: 512
dropout_rate: .1

num_negs: 1000
margin: 0.9
weight_for_negative: 100
unseen_only: False

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20