root: ../../data
dataset: Amazon2018Electronics_550_LOU

maxlen: 50
num_heads: 1
num_blocks: 2
embedding_dim: 64
hidden_dropout_rate: 0.5
attn_dropout_rate: 0.3

epochs: 500
batch_size: 2048
optimizer: GaLoreAdamW
lr: 1.e-3
weight_decay: 0.1
loss: BCE

rank: 16
update_proj_gap: 20
galore_scale: 0.05
proj_type: std

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10