root: ../../data
dataset: Allrecipes_MMSSL

embedding_dim: 64
num_layers: 2

epochs: 100
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-4

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20

eval_freq: 1