root: ../../data
dataset: Tiktok_MMSSL

embedding_dim: 64
num_layers: 3

epochs: 50
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-3

eval_freq: 1

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20