root: ../../data
dataset: Tiktok_MMSSL

embedding_dim: 64
epochs: 800
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-5

num_ui_layers: 2
num_ii_layers: 1

weight4mAdj: 0.2
weight4modality: 0.2
sampling_ratio: 0.7

vfile: visual_modality.pkl
tfile: textual_modality.pkl

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20