root: ../../data
dataset: Yelp2018_10104811_ROU

embedding_dim: 64
num_layers: 4

lr: 1.e-4
weight_decay: 1.e-6
epochs: 1000
batch_size: 2048
optimizer: adam
dropout_rate: 0.

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20