# Data
root: ../../data
dataset: Amazon2023Games_550_LOU

# Model
maxlen: 5
embedding_dim: 64
num_vert: 4
num_horiz: 16
dropout_rate: 0.5
num_poss: 3
num_negs: 2

# Training
epochs: 300
batch_size: 512
optimizer: adam
lr: 0.005
weight_decay: 1e-06

# Evaluation
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, HitRate@20, HitRate@50, NDCG@5, NDCG@10, NDCG@20, NDCG@50]
which4best: NDCG@10
