root: ../../data
dataset: Amazon2014Tools_550_LOU

maxlen: 20
embedding_dim: 64

epochs: 300
batch_size: 512
dropout_rate: 0.
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-6

alpha: 0.2

ranking: pool
monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10