root: ../../data
dataset: Amazon2014Beauty_550_LOU

maxlen: 50
num_heads: 1
num_blocks: 2
embedding_dim: 64
hidden_dropout_rate: 0.3
attn_dropout_rate: 0.5

epochs: 500
batch_size: 512
optimizer: SM3
lr: 1.e-3
loss: BCE

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10